### ISSUE TITLE
token auto refresh in Client + SSR

### ISSUE THREAD

**Issue by zakaria-chahboun** [supabase/gotrue-js#167]
Hi everyone! This is some issues + improvements for Authentication with supabase.

#### Issues:

This works but it isn’t ideal for the following reasons:
* Supabase stores the refresh token in localstorage which makes it vulnerable to XSS. This is done so the supabase-js client library can refresh the token on the users behalf.
* There’s no refresh mechanism on a SSR request.
* It doesn’t follow the best practices for JWTs on frontend clients.

#### Potential improvements:
Any improvement will likely make Supbase Auth more difficult to use, so what I’m proposing would be opt-in for users that want to improve their auth security.

* Allow configuration of the refresh endpoint so we can proxy the request to Supabase ourselves. This would allow us to set a refresh token in a cookie and remove it from localstorage. There would need to be some extra security work in order to make sure a client wasn’t sending the request directly to a Supabase auth endpoint.
* Expose a function to generate the cookie using just the token. This would save us having to generate Express-style request/response objects just to get the cookie.

#### Note:
> I garbed these information from this blog, You can read it:
https://www.ashleyconnor.co.uk/2021/06/24/authenticated-server-rendered-pages-with-sveltekit-and-supabase#issues

**Comment by Keithcat767** [comment]
I was going to make a similar thread. It is surprising to me that the solution is storing the JWT in local storage. I would really like to see an improvement to reduce security risks. For me, this is a deal breaker.

**Comment by hf** [comment]
Hey @zakaria-chahboun thank you for the feedback. Would you mind providing more information regarding your security concerns on these topics.

> * Supabase stores the refresh token in localstorage which makes it vulnerable to XSS. This is done so the supabase-js client library can refresh the token on the users behalf.

Local storage is equivalent (and more secure) than storing tokens in cookies. HTTP-Only cookies are not an option since Supabase Auth targets a wide variety of apps: web, mobile, mobile-web (React Native), desktop, etc.

> * There’s no refresh mechanism on a SSR request.

We've since published a guide on [server-side rendering](https://supabase.com/docs/guides/auth/server-side-rendering) to help you understand the flow and how to keep it secure.

> * It doesn’t follow the best practices for JWTs on frontend clients.

Would you mind pointing to practices we're not implementing?
 
> * Allow configuration of the refresh endpoint so we can proxy the request to Supabase ourselves. This would allow us to set a refresh token in a cookie and remove it from localstorage. There would need to be some extra security work in order to make sure a client wasn’t sending the request directly to a Supabase auth endpoint.

You can do this by controlling the Redirect URL allow list and implementing your own SPA that would set cookies if you need to. Be advised that this is going to cause a lot of edge case problems in modern-style apps with respect to refresh tokens.

> * Expose a function to generate the cookie using just the token. This would save us having to generate Express-style request/response objects just to get the cookie.

We are going to be working on PKCE authorization flows soon which should give you more control over the flow of JWT and refresh tokens.

(I'll close the issue for now since it's been inactive for a while, but do feel free to continue the discussion or re-open the issue.)
