### ISSUE TITLE
`supabase.auth.api.deleteUser(user_id, service_role)` should be `supabase.auth.api.deleteUser(user_id)` instead

### ISSUE THREAD

**Issue by kangmingtay** [supabase/gotrue-js#192]

**Comment by zakaria-chahboun** [comment]
No! should be both of them
In my server side, I did all the request by just the `anon` key cuz it's more safe and it did the job. But if i want to remove a user, i use this `supabase.auth.api.deleteUser(user_id, service_role) `

So it's not good to change it for this reason, Just add another one instead of remove the OLD one!

Thanks :tulip:

**Comment by kangmingtay** [comment]
outdated, see https://github.com/supabase/gotrue-js/blob/master/src/GoTrueApi.ts#L782
