### ISSUE TITLE
feature: Rename listUsers to findUsers and support filter search and sort params

### ISSUE THREAD

**Issue by dthyresson** [supabase/gotrue-js#196]
# Feature request

While the PR https://github.com/supabase/gotrue-js/pull/195 adds listUsers, perhaps it should be renamed findUsers since the GoTrue implementation supports a find filter using FindUsersInAudience that finds users with the matching audience with a filter option and a sort:

	if filter != "" {
		lf := "%" + filter + "%"
		// we must specify the collation in order to get case insensitive search for the JSON column
		q = q.Where("(email LIKE ? OR raw_user_meta_data->>'full_name' ILIKE ?)", lf, lf)
	}

	if sortParams != nil && len(sortParams.Fields) > 0 {
		for _, field := range sortParams.Fields {
			q = q.Order(field.Name + " " + string(field.Dir))
		}
	}

But, the only filter currently is email.

## Describe the solution you'd like

1. Rename listUsers to findUsers
2. Support option filter with explicit types like `byEmail` or `email`
3. Consider supporting sort params
4. Document

## Additional context

See: https://github.com/supabase/gotrue-js/issues/187

**Comment by hf** [comment]
This is a great suggestion. A couple of notes:

1. Filtering by arbitrary fields is problematic for scaling issues as larger projects with more than 1000 users will be draining the CPU / disk of the database.
2. Wildcard prefix/suffix queries can't use indexes so the same (or worse) scaling issues will occur.
3. Sorting and other facilities on arbitrary fields can incur very heavy resource usage, especially due to paging on sorted fields.

For this reason, we're unlikely to support arbitrary filtering and will be redoing much of the existing anyway to ensure a scalable and performant implementation.

Things we are likely to support when filtering:

1. Prefix search on email, phone number, other identity provider attributes (Twitter user ID).
2. Filtering by some categories: blocked / unverified / verified / identity provider...
3. Token-based pagination instead of page-offset pagination.

Since this spans both [gotrue](https://github.com/supabase/gotrue) and this library, I'm adding this to the team's backlog. No clear timeline on it yet. I'll close this issue but should people have more to contribute, do comment.
