### ISSUE TITLE
chore: handle redirectTo for email and phone signIn

### ISSUE THREAD

**Issue by awalias** [supabase/gotrue-js#217]
currently if a user sets [redirectTo option](https://github.com/supabase/gotrue-js/blob/edcd2ffde6dfe81d02700a52a79e635a5ab8839d/src/GoTrueClient.ts#L214) in conjunction with email+password or phone sign in, it is ignored.

suggestions:

- if `phone` and `redirectTo` are populated, we should print a warning message in the console
- if `email+password` and `redirectTo` are selected we should perform the redirect for the caller **on the client** and **after** the session is saved and notification sent
  - this increases DX because the user doesn't have to do the redirect themselves manually

NOTE: the email+password change is a **breaking change**, and should be released along with the OIDC and wallet connect additions in a new gotrue-js v2.0.0 (which we can promote along with "Crypto Logins")

**Comment by iamclaytonray** [comment]
What is the status of this? This is a major bug. Users signing into `x.com` are being redirect to `admin.x.com` if I update the `Site URL` option in the dashboard so that admins can update content for our app. I know I'm spamming every repo. For a week, I've been trying to get some sort of resolution. Hell, invite to whatever private repos and I'll fix the damn issue myself.

**Comment by kangmingtay** [comment]
Currently, email + password or phone + password sign-ins are making a [POST request to gotrue](https://github.com/supabase/gotrue-js/blob/862996337c38876eaefead036871ea10df2e27bd/src/GoTrueApi.ts#L144-L149) which doesn't accept a redirect_to param. We don't redirect the post request because the tokens are being sent back in the response body and redirecting the request would transform it into a GET request and strip out the response body. (as seen [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Redirections)).

@iamclaytonray you would have to handle the redirection on your own after receiving a response from the signIn method. For password-based sign-ins, you should listen for the "SIGNIN" event and redirect the user accordingly. 

@thorwebdev @dthyresson any ideas on improving the current flow for password-based sign-in methods?

**Comment by kangmingtay** [comment]
For password-based `signUp` methods, the `redirect_to` is appended to the confirmation link sent to the user's email. The `redirect_to` param doesn't redirect the user after the signUp has been completed. We should make this clear in the docs so it isn't confusing for the DX.
