### ISSUE TITLE
FetchError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by noskovvkirill** [supabase/gotrue-js#325]
# Bug report

## Describe the bug

Hi guys! I'm using Supabase in one of my projects and I face a really weird issue. First I thought it's related to the JS version of the superbase-js library (some people reported the same error). Updating the client fixed that, but then the issue reappeared again.
I see
`error {
  message: 'FetchError: invalid json response body at https://tcmqmkigakxeiuratohw.supabase.co/rest/v1/mirroritems_test?select=*&order=timestamp.desc.nullslast&limit=19 reason: Unexpected token < in JSON at position 0',
  details: '',
  hint: '',
  code: ''
}`

## To Reproduce
I use the alpha preview of functions. The last time Supabase was down it coincide with the function that was triggered. Not sure if it caused an issue or not. If I mock the data and trigger the function myself, it works correctly. 
I don't have a clue how to reproduce it exactly, it seems to me that it's not the issue with the client or framework I use. But just in case,  I use next.js "11.1.2" with  "@supabase/supabase-js": "^1.28.5",

Restarting the server seems to fix the issue. 

## Expected behavior

Stable runtime. 

## Screenshots

<img width="763" alt="issue" src="https://user-images.githubusercontent.com/50060130/145830719-8b279a53-9bdb-4b1e-b485-a145496fe2c7.png">

## System information

- OS: macOS
- Version of supabase-js  1.28.5
- Version of Node.js: v14.15.1

**Comment by satyapalsharma** [comment]
@J0 In my understanding deep down it is al related to a single problem. Where database is not responding in timely manner, Thus causing the related API to timeout. As Supabase client library always expect API response to be a valid JSON it is thrwoing errors on not getting one. But these are all related to the API timeout. 
There is something seriously wrong with the memory management/Reporting at supabase end. Anyone who is facing these issues just Increase the RAM and 90% of these issues will be gone, No matter how much RAM is free on your server.

**Comment by servedbyskull** [comment]
ran into same issue today! :|

**Comment by kangmingtay** [comment]
Hey everyone, just wanna check if this issue has been fixed? We noticed an issue with our internal api-gateway where there was an error parsing certain JWTs sent. We've since rectified the issue awhile back. 

I don't think that this is an issue with the gotrue-js client library as I can't seem to reproduce it while running gotrue locally and directly connecting to it via my client app. 

If anyone is still facing this issue, can you please reach out to us at [support](https://app.supabase.com/support/new) and we'll get to the bottom of it!

**Comment by hf** [comment]
Hey everyone, just want to give some context on errors that say `Unexpected token < in JSON at position 0`. This is a class of errors that occurs usually when the underlying server is down and the CDN is rendering a 5XX response page with HTML. The error comes because all HTML starts with `<!DOCTYPE...`.

If you see this, it's probably not connected to the way you're using the API and means that something crashed, is not reachable or timed out.

**Comment by STRd6** [comment]
What fixed it for me was using `encodeURIComponent` for my storage bucket path that had spaces in it. I assume that if the path isn't encoded properly it hits a bad url and the server responds with a non-json 404 response, hence the `< in jSON at position 0`
