### ISSUE TITLE
RFC: change localstorage in constructor to synchronous request 

### ISSUE THREAD

**Issue by kiwicopple** [supabase/gotrue-js#36]
# Feature request

## Is your feature request related to a problem? Please describe.

https://github.com/supabase/gotrue-js/blob/cccc4f49f6de8067b68c6892fa471a5dd544d4cb/src/GoTrueClient.ts#L57

Since the call to `_recoverSession` is async, it means that `currentSession` and `currentUser` isn't populated by the constructor, and that clients need to wait for the stateChangeEmmitter to fire.

This is causing a lot of problems [[1]](https://github.com/supabase/supabase/discussions/318#discussioncomment-144461) [[2]](https://github.com/supabase/supabase/issues/383)

## Describe the solution you'd like

LocalStorage is [synchronous](https://stackoverflow.com/questions/20231163/is-html5-localstorage-asynchronous), so we can remove the await. However we will need a way to handle it for ReactNative. 

Is there a way we can handle it for both situations?

## Additional context

Side note - I have seen some people [complaining](https://github.com/supabase/supabase/discussions/391#discussioncomment-224137) that globalThis is undefined. This is also related to storage. Should this also be updated to something that works everywhere?

https://github.com/supabase/gotrue-js/blob/cccc4f49f6de8067b68c6892fa471a5dd544d4cb/src/GoTrueClient.ts#L10

**Comment by kiwicopple** [comment]
@ykdojo @thorwebdev Any thoughts on this one? I guess we might be able to detect if the storage is `async` somehow? Or we can provide some sort of `sync` [storage](https://github.com/raphaelpor/sync-storage) for ReactNative users?

**Comment by ykdojo** [comment]
I wonder if we can make two versions of  _recoverSession() (async and sync), and decide which one to use by detecting whether or not the user's using React Native here:

https://github.com/supabase/gotrue-js/blob/cccc4f49f6de8067b68c6892fa471a5dd544d4cb/src/GoTrueClient.ts#L57

**Comment by kiwicopple** [comment]
I like that idea @ykdojo 

Not sure how we can detect if local storage is async, but i guess can run the `sync` function from the constructor and then let it fail silently.

**Comment by thorwebdev** [comment]
To be clear, on web `this._recoverSession() ` is currently synchronous because localStorage reads on web are synchronous, so here the await shouldn't have any effect. Only if we're running on a non-web platform like React Native and using async storage this should have an effect.

So not entirely sure if there's a different issue at play here.

**Comment by thorwebdev** [comment]
Also, you will need the [`onAuthStateChange` event handler](https://supabase.io/docs/client/auth-onauthstatechange) anyway, because we might be recovering the session from the refresh token in which case and async server request is involved: https://github.com/supabase/gotrue-js/blob/master/src/GoTrueClient.ts#L366, so there really isn't a way around having that handler. So I wonder if this is more about better documentation on the `onAuthStateChange` handler?

**Comment by yigitest** [comment]
`this.__recoverSession()` is currently is `async` because it is defined as `aysnc`. When you call `this._recoverSession()` from the `GoTrueClient::constructor()`, it will be called, executed and finished some time in the future. Maybe 0ms from now, maybe 100ms. 

I'm not an experienced JS developer. Maybe you could be right in this case. It depends on the implementation. But this is how concurrency in computer systems in general works.

**Comment by gawlk** [comment]
Hi, any news ?

**Comment by kiwicopple** [comment]
I coded up a solution here, with this caveat:

https://github.com/supabase/gotrue-js/pull/68/files#r598291376

I don't know if I would call it a bug - in many cases we need to verify that the token is still valid, and if it's not valid we need to make a request to the server to refresh the token. This requires an API call, so there is no way we can synchronously return a new session from the constructor.

This change will solve any problems that people are having with refreshing the page however. If there is a valid session (set up within the last 60 mins) it will be immediately returned from the constructor
