### ISSUE TITLE
Reset Password (via email) workflow

### ISSUE THREAD

**Issue by piehouserat** [supabase/gotrue-js#365]
Currently working on implementing password reset and running into a few issues.

I use `supabaseClient.auth.api.resetPasswordForEmail()` to email the user a link which is fine.

Upon clicking the link I notice that the user is immediately logged in as both the `SIGNED_IN` and `PASSWORD_RECOVERY` events are fired. I could use the `PASSWORD_RECOVERY` event to sign out the user and redirect them to a change password form page although this seems a bit strange. I would not expect a user to be automatically signed in if clicking on a password reset link.

I also notice the [docs are out of date](https://supabase.com/docs/reference/javascript/auth-onauthstatechange#notes) as they mention nothing about the `PASSWORD_RECOVERY` event, I found this via other github issues / code.

Would appreciate some guidance here :)

**Comment by kangmingtay** [comment]
Hey @piehouserat,

> I would not expect a user to be automatically signed in if clicking on a password reset link.
This is currently the behaviour of gotrue. A password reset link is basically a magiclink. After the user is logged in, you can make use of the redirect url to redirect the user to a page to enter a new password and call the [`supabase.auth.update` method](https://github.com/supabase/gotrue-js/blob/master/src/GoTrueClient.ts#L360) or the [`supabase.auth.updateUser` method if you're on v2](https://github.com/supabase/gotrue-js/blob/rc/src/GoTrueClient.ts#L501). 

Hope this helps! We won't be changing this default behaviour any time soon since it seems like a major breaking change for those who are accustomed to the current behaviour.
