### ISSUE TITLE
GoTrueClient is unable to retrieve session when setting accessToken in global.headers for SSR applications

### ISSUE THREAD

**Issue by miguel-flowalytics** [supabase/gotrue-js#450]
# Bug report

## Describe the bug

After removing `setAuth` it's recommend to set an `accessToken` via `global.headers`. Here's an example: https://github.com/supabase/gotrue-js/pull/340#issuecomment-1218065610

Unfortunately, this breaks auth functionality. I'm unable to retrieve a session using `getSession()` or user with `getUser()` (which relies on getSession).

But I'm able to make requests to select data.

![cleanshot_09_22_at_11_18@2x](https://user-images.githubusercontent.com/111984925/191788826-961a400f-9b54-4090-9242-97ddcffa43f9.png)

## To Reproduce

This is for a Remix project. So I took the advice to create a client per request, like so:
```
const supabase = createClient(supabaseUrl, supabaseKey, {
    auth: {
      autoRefreshToken: false,
      detectSessionInUrl: false,
      persistSession: false,
    },
    global: {
      headers: {
        Authorization: `Bearer ${accessToken}`,
      },
    },
  });
```

Because this is a SSR application, there's no need to `persistSession`.
But this is the very option that blocks the client from getting a session. `GoTrueClient._initialize` does not set `this.inMemorySession`

Another thing,  I'm using on Remix's `createCookieSessionStorage` API. Which handles setting cookie session for the user. I extract the access token from this API and then set it in `createClient`. I'm handling refresh token logic in the Remix route level.

1. createClient per request as advised [here](https://github.com/supabase/supabase-js/issues/514#issuecomment-1218513303)
2. Call `getSession`
3. Get no session or user

## Expected behavior

I should be able to retrieve session and user information. 
This is necessary to handle refreshToken logic at the server-side route level.

## Screenshots

attached under **Describe the bug**

## System information

- OS: macOS
- Browser (if applies) chrome
- Version of supabase-js: 2.0.0-rc.10
- Version of Node.js: v16.16.0

## Additional context
* If this is an intended behavior of removing `setAuth`, how to handle refresh token logic in a SSR application?

**Comment by galizar** [comment]
I'm having this issue too with the latest RC. As far as I can tell by looking at the source passing the `Authorization` header should be enough to have the `getUser` method work, but it just returns `null`. Just as you said, I'm able too to make queries to the database that require auth. I have a couple of commands that use `getUser` for insert, those ones do fail because `getUser` returns null.

**Comment by miguelespinoza** [comment]
yup, I had to downgrade to v1 for now. I don't have time to fix this issue. Granted, I already had to fix a refresh token issue for chrome extensions two weeks ago.

This is simply an oversight. Hopefully, this can be addressed soon. It's just a matter of having access to that header that was passed when initializing supabase. Ideally with the session and user already in memory.

**Comment by galizar** [comment]
I think I see what's the issue: The `getUser` method extracts the Authorization header and passes it to the `_request` method _as is_: 
https://github.com/supabase/gotrue-js/blob/v2.0.0-rc.5/src/GoTrueClient.ts#L481.

But, the `_request` method expects the `jwt` option to be just the JWT part of the header, meaning, the Authorization header value would be overridden in that method to be `Bearer Bearer JWT`: 
https://github.com/supabase/gotrue-js/blob/v2.0.0-rc.5/src/lib/fetch.ts#L85.

I may be missing something though as I haven't tried modifying the source yet.

**Comment by dwaynelavon** [comment]
This issue also affects resetting passwords for users. Once the user clicks the link in their email, the redirects and client session process works well. But, when the server tries to call updateUser, a "Auth session missing!" error is thrown. Note: other methods seem to work fine, but updateUser ignores the auth header.

**Comment by kangmingtay** [comment]
> But, the _request method expects the jwt option to be just the JWT part of the header, meaning, the Authorization header value would be overridden in that method to be Bearer Bearer JWT

Hi @galizar, we've just fixed this issue in the latest version so this should allow you to call `getUser` successfully as long as the authorization header you are setting has not expired. 

As for retrieving the session, since this is usually called on the server-side or in an SSR context, we acknowledge that the auth flow is rather cumbersome for now because you need to send the tokens from the client to the server (via cookies ideally). 

This is the current workaround we're proposing:

1. [Create a client per request](https://github.com/supabase/supabase-js/issues/514#issuecomment-1218513303)
2. Call [`setSession`](https://github.com/supabase/gotrue-js/blob/rc/src/GoTrueClient.ts#L539) with the access token and refresh token you passed in the cookies. 
3. If the access token has expired, `setSession` will handle refreshing the session for you using the refresh token and save the session in memory in the client you created.
4. Continue to perform whatever authenticated request your app requires.

We're working on a proper server-side auth guide in our documentation to highlight these steps. Thanks everyone for all the feedback and taking the time to comment on this issue! 

Let me know if this works for yall!

**Comment by lucis** [comment]
@kangmingtay I was hoping that `setSession` would include user's credentials in headers, but I noticed that it doesn't. Do you have any idea why?

I implemented [this approach](https://supabase.com/docs/guides/auth/server-side-rendering#bringing-it-together) and noticed that my calls to the database were not authenticated (RLS wouldn't work). It got fixed after I added `global.headers.Authentication`.

**Comment by hf** [comment]
Closing since this has been fixed with v2 of the library. Please read our [server side rendering](https://supabase.com/docs/guides/auth/server-side-rendering) guide for more information on best practices.

**Comment by therecluse26** [comment]
@hf I'm not using SSR, just an SPA, but still running into this issue with gotrue-js v2.54 when trying to call `updateUser` in the password update flow. Any idea what I might be doing wrong?

This is the whole code block I'm working with.

![image](https://github.com/supabase/gotrue-js/assets/8239106/6b99d69a-965f-49a4-a333-8d44e4efaebe)
