### ISSUE TITLE
auth.getSession returns no data

### ISSUE THREAD

**Issue by simpautus** [supabase/gotrue-js#496]
Hi!

I'm trying to get the current session by calling `getSession()` from the server (Remix action) after creating a client with Auth header. I get the user by calling `getUser()` but `getSession()` returns `{ data: { session: null }, error: null }`.

I'm on version 2.0.0

**Comment by kangmingtay** [comment]
> However, the client still knows nothing about a supabase session.

Yeah, if you are using the supabase client on the server-side, you need to also call `setSession` and pass the session details in via the request to the server. `setSession` will help to initialise the session on the server-side. Hope this helps!

**Comment by j4w8n** [comment]
@simpautus have you tried the above solution with setSession? Not sure why I didn't think of that before. Can probably set that right before/after you set the auth header.

**Comment by j4w8n** [comment]
@kangmingtay ok, using `setSession` "works", but not conveniently.

I'm creating the server client with `persistSession` and `autoRefreshToken` set to `false`.
I'm running `setSession()`, and it does indeed return a session. This is being done in a central server-side location of the app (`hooks.server.js` in SvelteKit to be exact), because this is the best place to read the cookies. If I immediately run `getSession` here, then yes, it returns the session.

However, this isn't the location where I want to use the server client. There could be many of them where I'm actually using the client. If I go to one of those files and run `getSession`, it returns null with no errors.

I'm guessing this is because of the way `this.inMemorySession` in the GoTrueClient.ts works. Once I import the server client in a different location, the "memory" isn't the same.

I can work around this in SvelteKit, but it would be more boilerplate code. I'd have to grab the cookies in each server-side file where I want to use the client, then call `setSession`, followed by `getSession`.

I don't know anything about Remix, so I'll let @simpautus speak to whether the workaround is possible there.

I think being able to optionally pass in an `access_token` jwt to `getSession` would be much cleaner.
And there's always a chance there's something I'm not thinking of here.

**Comment by j4w8n** [comment]
Now that I think about it. There's no reason to call getSession right after setSession, since set will return the session.

**Comment by simpautus** [comment]
> @kangmingtay ok, using `setSession` "works", but not conveniently.
> 
> I'm creating the server client with `persistSession` and `autoRefreshToken` set to `false`. I'm running `setSession()`, and it does indeed return a session. This is being done in a central server-side location of the app (`hooks.server.js` in SvelteKit to be exact), because this is the best place to read the cookies. If I immediately run `getSession` here, then yes, it returns the session.
> 
> However, this isn't the location where I want to use the server client. There could be many of them where I'm actually using the client. If I go to one of those files and run `getSession`, it returns null with no errors.
> 
> I'm guessing this is because of the way `this.inMemorySession` in the GoTrueClient.ts works. Once I import the server client in a different location, the "memory" isn't the same.
> 
> I can work around this in SvelteKit, but it would be more boilerplate code. I'd have to grab the cookies in each server-side file where I want to use the client, then call `setSession`, followed by `getSession`.
> 
> I don't know anything about Remix, so I'll let @simpautus speak to whether the workaround is possible there.
> 
> I think being able to optionally pass in an `access_token` jwt to `getSession` would be much cleaner. And there's always a chance there's something I'm not thinking of here.

Sorry for letting you wait. 

My initial problem was getting the session server-side with the `access_token` after an OAuth callback. I thought `getSession` would do exactly that but I had to use `setSession` instead. It seems to work although the documentation is  lacking a little in terms of what parameters to provide. I'm passing both `access_token` and `refresh_token`.

Now I'm facing another weird issue where my `onAuthStateChange` subscription is triggered randomly after a successful Oauth login. It's located in the `useEffect` of a root component. I'm logging that the listener subscription gets set but sometimes the events are fired and sometimes not. But maybe that belongs to another topic.

**Comment by kangmingtay** [comment]
Hi @simpautus, is the oauth callback redirecting you to the server-side? Currently, we don't support redirecting to a server-side environment because gotrue returns the access / refresh tokens in the query fragment which can't be parsed on the server-side. You would need the oauth callback to redirect to the client-side first and then call your server-side endpoint and pass in the access / refresh tokens stored in the browser / local storage.

**Comment by simpautus** [comment]
Hi! I was able to sort out what I needed in this issue by using `setSession`.

If you mean the onAuthStateChange issue it's better described [here](https://github.com/supabase/gotrue-js/issues/518)

The redirects are client side.

**Comment by hf** [comment]
Looks like this is no longer an issue. Please reopen if that's not the case.
