### ISSUE TITLE
Reset password email template URL differs between Supabase admin UI and SupabaseJS

### ISSUE THREAD

**Issue by evansaa1** [supabase/gotrue-js#545]
# Bug report

## Describe the bug

When implementing self service reset password functionality via SupabaseJS I have noticed that the redirect URL that's populated in the email template has an additional forward slash when generated from the Supabase admin UI compared to the Supabase JS client (v1.x)

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a reset password email template in the Supabase admin UI and include a link to your "choose a new password" page. E.g. `<a href="{{ .ConfirmationURL }}/resetpassword">Reset Password</a>`
2. Test that the template works and redirects as expected by selecting Reset Password against a user in the Supabase admin UI.
3. Without modifying the template send a reset password request via the Supabase JS client by calling
```
await supabase.auth.api.resetPasswordForEmail(email, {
      redirectTo: "login",
    });
```
4. Observe that the link in the password reset email is broken because it has an additional forward slash in the redirect_to query string param link e.g. https://xyz.supabase.co/auth/v1/verify?token=some_token&type=recovery&redirect_to=http://localhost:3000//resetpassword

## Expected behavior

The same link to be generated in both cases

## System information

- OS: MacOS
- Browser: Firefox
- Version of supabase-js: 1.35.7
- Version of Node.js: 16.14.2

## Additional context

So far I have only tested this against localhost

**Comment by hf** [comment]
This is not a recommended approach:

> Create a reset password email template in the Supabase admin UI and include a link to your "choose a new password" page. E.g. `<a href="{{ .ConfirmationURL }}/resetpassword">Reset Password</a>`

The `{{ .ConfirmationURL }}` is a URL that is [computed deep within GoTrue](https://github.com/supabase/gotrue/blob/master/mailer/template.go#L224-L248).

You can use the [`redirectTo` option](https://supabase.github.io/gotrue-js/v2/classes/GoTrueClient.html#resetPasswordForEmail) to set a *full URL* where you want the user to be taken to. This URL must be added to the redirect URL allow list otherwise the Site URL will be used.

As for @renardeinside:

> For a second, it generates a strange link that is somehow incorrect, the link looks like this:

This is expected. The `#param` part is how Supabase Auth sends access and refresh tokens to your SPA. Fragments are not sent to the server.
