### ISSUE TITLE
Allow "remember me" option when signing in

### ISSUE THREAD

**Issue by user72356** [supabase/gotrue-js#571]
At present, signIn() stores the auth token in local storage by default, unless `persistSession` is false when creating the Supabase client. If `persistSession` is false, the session is not persisted at all and will not survive a page reload.

I would like to request that an option be given in the signIn() function to request that the session be remembered (the token is stored in local storage), or not remembered (the token is stored in session storage).

This will enable the common pattern of destroying the user session when the user closes the browser and the "remember me" checkbox was unchecked at login.

At present, the best I can do when the user unchecks the "remember me" box is to create a new Supabase client upon login with the option `persistSession` turned off. It's kinda clunky to have to create a new client just to supply this option and it still doesn't solve the problem in the generally expected way, since a simple page reload will log the user out, rather than a browser close.

**Comment by hf** [comment]
Hey this is possible (tho not particularly clean) to do today.

You can use the [`storage`](https://supabase.github.io/gotrue-js/v2/modules.html#GoTrueClientOptions) option when creating a client and specify `window.sessionStorage` instead of `window.localStorage` (which is used by default).

I'll add this to our feedback board so we consider it when we get a chance.
