### ISSUE TITLE
inviteUserByEmail() redirectTo param doesn't properly match Redirect URLs

### ISSUE THREAD

**Issue by user72356** [supabase/gotrue-js#667]
`supabase.auth.admin.inviteUserByEmail(email, { redirectTo })` doesn't properly match the setup in the Redirect URLs section of the dashboard. 

Per the doc I added `http://localhost:8888/**` into the Redirect URLs setting and this works when signing up with `supabase.auth.signUp({ email, password, options: { emailRedirectTo: "http://localhost:8888" } })`.

However, the exact same setup behaves differently with `supabase.auth.admin.inviteUserByEmail(email, { redirectTo: "http://localhost:8888" })`. In this case I'm being redirected to the main URL present in the Site URL setting, because `http://localhost:8888` is not matching the pattern for some reason. Only when I add `http://localhost:8888` (note the absence of trailing slash), does the redirect work with `inviteUserByEmail()`.

So I have to add both `http://localhost:8888/**` AND `http://localhost:8888` in the Redirect URLs setting, only for `inviteUserByEmail()`!

**Comment by kangmingtay** [comment]
Hi @user72356 and @lifeiscontent, this is the expected behaviour. This is because the `/` character is treated as a separator so just simply having `http://localhost:8888/**` wont allow `http://localhost:8888` but will allow `http://localhost:8888/`

@lifeiscontent can you elaborate more on what you mean by overriding all of the redirectUrls? If you add the redirect URLs to the additional redirect urls config on the dashboard, you should be able to specify them when calling `signUp` or `resetPasswordForEmail`. If you are not being redirected to the specified redirect URL, it means that you are not specifying them correctly in the allow list.

**Comment by kangmingtay** [comment]
@user72356 @lifeiscontent closing this issue because we haven't heard back but feel free to reopen this if it's still a problem for you
