### ISSUE TITLE
Session not recovering in React Native

### ISSUE THREAD

**Issue by WJimmyCook** [supabase/gotrue-js#76]
# Bug report

## Describe the bug

Initializing the client doesn't recover the session from AsyncStorage

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Login a react native app
2. Close the app
3. Reopen the app

## Expected behavior

Session should be restored when opening the app

## System information

- OS: macOS
- React Native 0.63.4
- @supabase/gotrue-js: 1.12.4
- @supabase/postgrest-js: 0.28.0
- @supabase/realtime-js: 1.0.6

## Additional context

If I uncomment these lines then everything works as expected. (https://github.com/supabase/gotrue-js/blob/master/src/GoTrueClient.ts
)
```
//should be handle on _recoverSession method already
this._saveSession(currentSession)
this._notifyAllSubscribers('SIGNED_IN')
```

**Comment by jaredramirez** [comment]
I believe the reason it works in `_recoverAndRefresh` and not `_recoverSession` is because RN's `AsyncStorage.getItem` returns a promise. In `_recoverAndRefresh`, it's called like `await this.localStorage.getItem(STORAGE_KEY)`. This succeeds, but doesn't actually save the recovered session because those two lines are commented out. In`_recoverSession`, it's called like `this.localStorage.getItem(STORAGE_KEY)` (no `await`), and this fails with:
```
error [SyntaxError: JSON Parse error: Unexpected identifier "object"]
```
I think this is because it's trying to call `JSON.parse` on something like `[Object object]` (the result of coercing a Promise to a string) . This would explain why commenting those two lines in `_recoverAndRefresh` fixes the problem.

A quick fix should be as simple as re-commenting the two lines in `_recoverAndRefresh` with a quick comment explaining why it's necessary.

**Comment by jaredramirez** [comment]
I think this can be closed now because of https://github.com/supabase/gotrue-js/commit/56b6feb44f4e5eb5b166d9512d9a3356bb9e0f0d. Thanks @phamhieu!

**Comment by kiwicopple** [comment]
🎉
